### ISSUE TITLE
Tiles loading in irregular way in blazor hybrid(.net maui)

### ISSUE THREAD

**Issue by shivam286** [bjtrounson/BlazorLeafletInterop#33]
Hi,
The maps are only loading tile layer also in irregular way in .net maui blazor hybrid also the canvas was found to be not loading. I've attached the ss.

the code I've used-
![image](https://github.com/bjtrounson/BlazorLeafletInterop/assets/52860385/a3a65124-b240-40e4-ab4c-0c3cc470e3ea)

the view I'm getting(notice the seams)-
![image](https://github.com/bjtrounson/BlazorLeafletInterop/assets/52860385/4e9a56b9-2b15-468b-add6-c5b84b84505f)

the div's are found to be not loading-
![image](https://github.com/bjtrounson/BlazorLeafletInterop/assets/52860385/40ad7fc1-e8fb-4832-85e1-879d7e6a8123)

whereas in the example blazor app you have provided the div's are loading completely.

**Comment by bjtrounson** [comment]
Hi,

Sorry it has taken me so long to reply to this only saw this today.
I think the problem here is the wrapping layout "article" element in the MainLayout.razor seems to be messing with Leaflet a bit. If that doesn't fix it I would assume there is some other CSS styling messing with it. I wasn't able to fully reproduce your tiles being mis-aligned from your screen shots, but I was able to get a working example going.

It's .NET 8 project so hopefully that won't cause any issues
Here is the link to the [repo]( https://github.com/bjtrounson/BlazorLeafletInteropMAUIExample)
It is a similar example as in this repo for WASM, so there is probably some extra stuff that you can just remove in there.
Hopefully is helps fix the issues you might be having or at least gives you a base to somewhat build from.

Regards,
Ben
